name: Build master branch

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: openjdk@1.14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_PAT }}
      run: |
        ./gradlew build
        ./gradlew publish
